= ctypes demo: zstd

Based on https://github.com/ygrek/ocaml-zstd[ocaml-zstd]. Modified to demonstrate https://github.com/obazl/rules_ctypes[rules_ctypes].


By default, obtains Bazel module `zstd` from the Bazel Central
 Registry, which builds `libzstd.a`.  In MODULE.bazel:

    bazel_dep(name = "zstd", version = "1.5.5")

To build using a precompiled system library, edit the ‘new_local_repository` directive
 at the bottom of link:MODULE.bazel[MODULE.bazel], and pass
 `--//stubs:local‘, e.g.

    $ bazel test test --//stubs:local

To see what Bazel does, first run `source ../tools/source.me`. This
defines an alias, `bl` (“browse log”), which allows you to easily
browse the Bazel command log after you run a Bazel command. Then when
you run a command, pass `--config=showpp`; this enables the `showpp`
config group defined in link:.bazelrc[.bazelrc]. This tells Bazel to
pretty-print all the commands it executes.

You can also use `aquery` to tell Bazel to show commands without actually running them:

    $ bazel build stubs:zstd_api



== The `ctypes_module` rule

`ctypes_module` is a macro that expands to a dozen or so targets. See https://github.com/obazl/rules_ctypes[rules_ctypes] for more information.

The main build target is set by the `api_name` attribute; in this case,
`zstd_api`:

    $ bazel build stubs:zstd_api

To view the entire expansion:

    $ bazel cquery stubs:all --output=build

You can also see the expansion of a single target:

    $ bazel cquery stubs:zstd_types_wrapper --output=build

Any of the generated targets can be built:

    $ bazel build  stubs:zstd_types_wrapper --config=showpp
    $ bazel build stubs:zstd_CtypesTYPE.ml --config=showpp

To see a list of files generated when targets in `//stubs` are built:

    $  bazel query 'kind("generated file", //stubs:*)'

== local system lib

Ends up in `external/+_repo_rules+local.zstd/lib/libzstd.a‘ which
indicates it was made by a repository_rule. Inspect that dir and
you’ll see its all symlinks to the sys lib; e.g.

    /opt/homebrew/Cellar/zstd/1.5.5


